[package]
name = "practica-01-declaracion-variables"
version = "0.1.0"
edition = "2024"
description = "Práctica: Declaración de variables inmutables y mutables"
authors = ["Bootcamp Rust"]

[dependencies]
